---
###################################################################################################
# it is intended that this configuration can be used with Vagrant (in Vagrantfile) and within
# Ansible (e. g. to adapt the /etc/hosts). 
#
vbox_image:
    name: minimal/trusty64
machines:
    MANAGEMENT:
      ip_address: 192.168.1.50
      hostname: management
    NODE1:
      ip_address: 192.168.1.10
      hostname: node1
    NODE2:
      ip_address: 192.168.1.20
      hostname: node2
      